namespace Broker.SourceGenerator.Generators;

[Generator]
public sealed class HandlerSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            context.CompilationProvider, (productionContext, compilation) =>
            {
                var registrationLines = new StringBuilder();

                foreach (var syntaxTree in compilation.SyntaxTrees)
                {
                    registrationLines.Append(ProcessSyntaxTree(syntaxTree, compilation));
                }

                registrationLines.AppendLine("services.AddScoped<ISender, Sender>();");

                GenerateServiceCollectionExtension(productionContext, registrationLines.ToString());
            }
        );
    }

    private string ProcessSyntaxTree(
        SyntaxTree syntaxTree,
        Compilation compilation
    )
    {
        var registrationLines = new StringBuilder();
        var semanticModel = compilation.GetSemanticModel(syntaxTree);

        foreach (var classDeclaration in syntaxTree.GetClassDeclarationSyntax())
        {
            if (semanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol symbol)
                continue;

            foreach (var @interface in symbol.Interfaces)
            {
                if (@interface.Name == "IHandler")
                {
                    if (symbol.IsGenericType)
                    {
                        var commandType = @interface.TypeArguments[0];

                        if (commandType is INamedTypeSymbol genericCommandType && genericCommandType.IsGenericType)
                        {
                            var handlerNamespace = symbol.ContainingNamespace;
                            var handlerName = symbol.Name.Split('`')[0];
                            var commandNamespace = genericCommandType.ContainingNamespace;
                            var commandName = genericCommandType.Name.Split('`')[0];

                            registrationLines.AppendLine($"services.AddScoped(typeof({handlerNamespace}.{handlerName}<>), typeof({commandNamespace}.{commandName}<>));");
                        }
                    }
                    else
                    {
                        var handlerType = symbol.ToString();
                        registrationLines.AppendLine($"services.AddScoped(typeof({@interface}), typeof({handlerType}));");
                    }
                }
                else if (@interface.Name.StartsWith("IRequestPreProcessor"))
                {
                    if (symbol.IsGenericType)
                    {
                        var preProcessorType = symbol.ToString().Split('`')[0] + "<>";
                        var interfaceType = @interface.ToString().Split('`')[0] + "<>";
                        registrationLines.AppendLine($"services.AddScoped(typeof({interfaceType}), typeof({preProcessorType}));");
                    }
                    else
                    {
                        var preProcessorType = symbol.ToString();
                        registrationLines.AppendLine($"services.AddScoped(typeof({@interface}), typeof({preProcessorType}));");
                    }
                }
                else if (@interface.Name.StartsWith("IRequestPostProcessor"))
                {
                    if (symbol.IsGenericType)
                    {
                        var postProcessorType = symbol.ToString().Split('`')[0] + "<>";
                        var interfaceType = @interface.ToString().Split('`')[0] + "<>";
                        registrationLines.AppendLine($"services.AddScoped(typeof({interfaceType}), typeof({postProcessorType}));");
                    }
                    else
                    {
                        var postProcessorType = symbol.ToString();
                        registrationLines.AppendLine($"services.AddScoped(typeof({@interface}), typeof({postProcessorType}));");
                    }
                }
            }
        }

        return registrationLines.ToString();
    }

    private void GenerateServiceCollectionExtension(
        SourceProductionContext context,
        string registrations
    )
    {
        var handlerServiceCollectionExtensionsSource =
            $$"""
              // <auto-generated />
              using Microsoft.Extensions.DependencyInjection;
              using Broker.Abstractions;

              namespace Broker.SourceGenerator;

              public static class HandlerServiceCollectionExtensions
              {
                 public static void AddHandlers(this IServiceCollection services)
                 {
                    {{registrations}}
                 }
              }
              """;

        context.AddSource(
            "HandlerServiceCollectionExtensions.g.cs",
            handlerServiceCollectionExtensionsSource
        );
    }
}